#!/bin/bash

# Print out help
for arg in "$@"; do
    if [[ "$arg" = "-h" || "$arg" = "--help" ]]; then
        echo "Usage: `basename $0` PATH
        
A wrapper for 'go build' that assigns the latest commit hash and comment to a
a global variable 'buildCommit', the date to 'buildDate', and the go runtime
version to 'buildRuntime'.  These need to be declared in the main package."
        exit
    fi
done

ARG=$1

if [[ "$ARG" = "" ]]; then
    ARG="."
fi
if [[ ! -e "$ARG" ]]; then
    echo "`basename $0`: must specify valid path"
    exit 1
fi

LOC=$ARG

if [[ -f "$LOC" ]]; then
    DIR="$( dirname "$( realpath "$ARG" )" )"
else
    DIR=$LOC
fi
cd $DIR
# Remove any quotes to avoid parsing weirdness
COMMIT="`git log --abbrev-commit --oneline -n 1 | sed s/\'//g | sed 's/\\\"//g'`"
DATE="`date -u '+%Y.%m.%d %H:%M:%S'` UTC"
RUNTIME="`go version | sed -En 's/.*(go[^ ]+).*/\1/p'`"
LDFLAGS="-X main.buildCommit '$COMMIT' -X main.buildDate '$DATE' -X main.buildRuntime '$RUNTIME'"

which goat &> /dev/null
if [[ "$?" -eq "0" ]]; then
    goat build -ldflags "$LDFLAGS" $LOC
else
    go build -ldflags "$LDFLAGS" $LOC
fi
